### ISSUE TITLE
ガード句

### ISSUE THREAD

**Issue by takashi-sakai** [HiroshiHayano/eg_sns#1]
https://github.com/HiroshiHayano/eg_sns/blob/b8fe15de2fa160cf0a1dfd3fbc5fffa0620c2ffb/app/Controller/AnswersController.php#L21

例外をthrowしているのでelse条件は要らないね。

**Comment by HiroshiHayano** [comment]
cakePHP2.3から$this->request->onlyAllow()が用意されてるのでそちらを使いました
